export type Skill =  {
  id: string;
  name: string;
  category: string;
}

export const allSkills: Skill[] = [
  // Programming Languages
  { id: "html", name: "HTML", category: "Programming Languages" },
  { id: "html5", name: "HTML5", category: "Programming Languages" },
  { id: "css", name: "CSS", category: "Programming Languages" },
  { id: "css3", name: "CSS3", category: "Programming Languages" },
  { id: "javascript", name: "JavaScript", category: "Programming Languages" },
  { id: "typescript", name: "TypeScript", category: "Programming Languages" },
  { id: "python", name: "Python", category: "Programming Languages" },
  { id: "java", name: "Java", category: "Programming Languages" },
  { id: "csharp", name: "C#", category: "Programming Languages" },
  { id: "cpp", name: "C++", category: "Programming Languages" },
  { id: "c", name: "C", category: "Programming Languages" },
  { id: "go", name: "Go", category: "Programming Languages" },
  { id: "rust", name: "Rust", category: "Programming Languages" },
  { id: "kotlin", name: "Kotlin", category: "Programming Languages" },
  { id: "swift", name: "Swift", category: "Programming Languages" },
  { id: "php", name: "PHP", category: "Programming Languages" },
  { id: "ruby", name: "Ruby", category: "Programming Languages" },
  { id: "scala", name: "Scala", category: "Programming Languages" },
  { id: "perl", name: "Perl", category: "Programming Languages" },
  { id: "r", name: "R", category: "Programming Languages" },
  { id: "matlab", name: "MATLAB", category: "Programming Languages" },
  { id: "sql", name: "SQL", category: "Programming Languages" },
  { id: "bash", name: "Bash/Shell", category: "Programming Languages" },
  { id: "powershell", name: "PowerShell", category: "Programming Languages" },

  // Frontend Frameworks & Libraries
  { id: "react", name: "React.js", category: "Frontend" },
  { id: "nextjs", name: "Next.js", category: "Frontend" },
  { id: "vue", name: "Vue.js", category: "Frontend" },
  { id: "nuxt", name: "Nuxt.js", category: "Frontend" },
  { id: "angular", name: "Angular", category: "Frontend" },
  { id: "svelte", name: "Svelte", category: "Frontend" },
  { id: "sveltekit", name: "SvelteKit", category: "Frontend" },
  { id: "solidjs", name: "Solid.js", category: "Frontend" },
  { id: "astro", name: "Astro", category: "Frontend" },
  { id: "remix", name: "Remix", category: "Frontend" },
  { id: "gatsby", name: "Gatsby", category: "Frontend" },
  { id: "jquery", name: "jQuery", category: "Frontend" },
  { id: "redux", name: "Redux", category: "Frontend" },
  { id: "zustand", name: "Zustand", category: "Frontend" },
  { id: "mobx", name: "MobX", category: "Frontend" },
  { id: "recoil", name: "Recoil", category: "Frontend" },

  // CSS & Styling
  { id: "tailwind", name: "Tailwind CSS", category: "CSS & Styling" },
  { id: "sass", name: "Sass/SCSS", category: "CSS & Styling" },
  { id: "less", name: "Less", category: "CSS & Styling" },
  {
    id: "styled-components",
    name: "Styled Components",
    category: "CSS & Styling",
  },
  { id: "emotion", name: "Emotion", category: "CSS & Styling" },
  { id: "bootstrap", name: "Bootstrap", category: "CSS & Styling" },
  { id: "material-ui", name: "Material UI", category: "CSS & Styling" },
  { id: "chakra-ui", name: "Chakra UI", category: "CSS & Styling" },
  { id: "ant-design", name: "Ant Design", category: "CSS & Styling" },
  { id: "shadcn", name: "shadcn/ui", category: "CSS & Styling" },
  { id: "radix", name: "Radix UI", category: "CSS & Styling" },
  { id: "headless-ui", name: "Headless UI", category: "CSS & Styling" },
  { id: "framer-motion", name: "Framer Motion", category: "CSS & Styling" },
  { id: "gsap", name: "GSAP", category: "CSS & Styling" },

  // Backend & Server
  { id: "nodejs", name: "Node.js", category: "Backend" },
  { id: "express", name: "Express.js", category: "Backend" },
  { id: "nestjs", name: "NestJS", category: "Backend" },
  { id: "fastify", name: "Fastify", category: "Backend" },
  { id: "django", name: "Django", category: "Backend" },
  { id: "flask", name: "Flask", category: "Backend" },
  { id: "fastapi", name: "FastAPI", category: "Backend" },
  { id: "spring", name: "Spring Boot", category: "Backend" },
  { id: "dotnet", name: ".NET", category: "Backend" },
  { id: "rails", name: "Ruby on Rails", category: "Backend" },
  { id: "laravel", name: "Laravel", category: "Backend" },
  { id: "graphql", name: "GraphQL", category: "Backend" },
  { id: "rest-api", name: "REST API", category: "Backend" },
  { id: "grpc", name: "gRPC", category: "Backend" },
  { id: "websockets", name: "WebSockets", category: "Backend" },
  { id: "microservices", name: "Microservices", category: "Backend" },

  // Databases
  { id: "postgresql", name: "PostgreSQL", category: "Databases" },
  { id: "mysql", name: "MySQL", category: "Databases" },
  { id: "mongodb", name: "MongoDB", category: "Databases" },
  { id: "redis", name: "Redis", category: "Databases" },
  { id: "sqlite", name: "SQLite", category: "Databases" },
  { id: "oracle", name: "Oracle", category: "Databases" },
  { id: "mssql", name: "SQL Server", category: "Databases" },
  { id: "cassandra", name: "Cassandra", category: "Databases" },
  { id: "dynamodb", name: "DynamoDB", category: "Databases" },
  { id: "firebase", name: "Firebase", category: "Databases" },
  { id: "supabase", name: "Supabase", category: "Databases" },
  { id: "prisma", name: "Prisma", category: "Databases" },
  { id: "drizzle", name: "Drizzle ORM", category: "Databases" },
  { id: "sequelize", name: "Sequelize", category: "Databases" },
  { id: "mongoose", name: "Mongoose", category: "Databases" },
  { id: "typeorm", name: "TypeORM", category: "Databases" },

  // Cloud & DevOps
  { id: "aws", name: "Amazon Web Services (AWS)", category: "Cloud & DevOps" },
  { id: "azure", name: "Microsoft Azure", category: "Cloud & DevOps" },
  { id: "gcp", name: "Google Cloud Platform", category: "Cloud & DevOps" },
  { id: "vercel", name: "Vercel", category: "Cloud & DevOps" },
  { id: "netlify", name: "Netlify", category: "Cloud & DevOps" },
  { id: "heroku", name: "Heroku", category: "Cloud & DevOps" },
  { id: "docker", name: "Docker", category: "Cloud & DevOps" },
  { id: "kubernetes", name: "Kubernetes", category: "Cloud & DevOps" },
  { id: "terraform", name: "Terraform", category: "Cloud & DevOps" },
  { id: "ansible", name: "Ansible", category: "Cloud & DevOps" },
  { id: "jenkins", name: "Jenkins", category: "Cloud & DevOps" },
  { id: "github-actions", name: "GitHub Actions", category: "Cloud & DevOps" },
  { id: "gitlab-ci", name: "GitLab CI/CD", category: "Cloud & DevOps" },
  { id: "circleci", name: "CircleCI", category: "Cloud & DevOps" },
  { id: "nginx", name: "Nginx", category: "Cloud & DevOps" },
  { id: "apache", name: "Apache", category: "Cloud & DevOps" },
  { id: "linux", name: "Linux", category: "Cloud & DevOps" },

  // Mobile Development
  { id: "react-native", name: "React Native", category: "Mobile Development" },
  { id: "flutter", name: "Flutter", category: "Mobile Development" },
  { id: "dart", name: "Dart", category: "Mobile Development" },
  { id: "ios", name: "iOS Development", category: "Mobile Development" },
  {
    id: "android",
    name: "Android Development",
    category: "Mobile Development",
  },
  { id: "expo", name: "Expo", category: "Mobile Development" },
  { id: "ionic", name: "Ionic", category: "Mobile Development" },
  { id: "xamarin", name: "Xamarin", category: "Mobile Development" },

  // Testing
  { id: "jest", name: "Jest", category: "Testing" },
  { id: "vitest", name: "Vitest", category: "Testing" },
  { id: "cypress", name: "Cypress", category: "Testing" },
  { id: "playwright", name: "Playwright", category: "Testing" },
  { id: "selenium", name: "Selenium", category: "Testing" },
  { id: "mocha", name: "Mocha", category: "Testing" },
  { id: "testing-library", name: "Testing Library", category: "Testing" },
  { id: "pytest", name: "pytest", category: "Testing" },
  { id: "junit", name: "JUnit", category: "Testing" },
  { id: "tdd", name: "Test-Driven Development", category: "Testing" },

  // Tools & Version Control
  { id: "git", name: "Git", category: "Tools & Version Control" },
  { id: "github", name: "GitHub", category: "Tools & Version Control" },
  { id: "gitlab", name: "GitLab", category: "Tools & Version Control" },
  { id: "bitbucket", name: "Bitbucket", category: "Tools & Version Control" },
  { id: "vscode", name: "VS Code", category: "Tools & Version Control" },
  { id: "vim", name: "Vim", category: "Tools & Version Control" },
  { id: "npm", name: "npm", category: "Tools & Version Control" },
  { id: "yarn", name: "Yarn", category: "Tools & Version Control" },
  { id: "pnpm", name: "pnpm", category: "Tools & Version Control" },
  { id: "webpack", name: "Webpack", category: "Tools & Version Control" },
  { id: "vite", name: "Vite", category: "Tools & Version Control" },
  { id: "esbuild", name: "esbuild", category: "Tools & Version Control" },
  { id: "turbopack", name: "Turbopack", category: "Tools & Version Control" },
  { id: "eslint", name: "ESLint", category: "Tools & Version Control" },
  { id: "prettier", name: "Prettier", category: "Tools & Version Control" },
  { id: "figma", name: "Figma", category: "Tools & Version Control" },
  { id: "postman", name: "Postman", category: "Tools & Version Control" },
  { id: "jira", name: "Jira", category: "Tools & Version Control" },

  // AI & Machine Learning
  { id: "tensorflow", name: "TensorFlow", category: "AI & Machine Learning" },
  { id: "pytorch", name: "PyTorch", category: "AI & Machine Learning" },
  {
    id: "scikit-learn",
    name: "Scikit-learn",
    category: "AI & Machine Learning",
  },
  { id: "keras", name: "Keras", category: "AI & Machine Learning" },
  { id: "opencv", name: "OpenCV", category: "AI & Machine Learning" },
  { id: "pandas", name: "Pandas", category: "AI & Machine Learning" },
  { id: "numpy", name: "NumPy", category: "AI & Machine Learning" },
  {
    id: "jupyter",
    name: "Jupyter Notebook",
    category: "AI & Machine Learning",
  },
  { id: "langchain", name: "LangChain", category: "AI & Machine Learning" },
  { id: "openai-api", name: "OpenAI API", category: "AI & Machine Learning" },
  {
    id: "huggingface",
    name: "Hugging Face",
    category: "AI & Machine Learning",
  },
  {
    id: "nlp",
    name: "Natural Language Processing",
    category: "AI & Machine Learning",
  },
  {
    id: "computer-vision",
    name: "Computer Vision",
    category: "AI & Machine Learning",
  },

  // Soft Skills
  { id: "problem-solving", name: "Problem Solving", category: "Soft Skills" },
  { id: "communication", name: "Communication", category: "Soft Skills" },
  { id: "teamwork", name: "Teamwork", category: "Soft Skills" },
  { id: "leadership", name: "Leadership", category: "Soft Skills" },
  { id: "agile", name: "Agile Methodologies", category: "Soft Skills" },
  { id: "scrum", name: "Scrum", category: "Soft Skills" },
  {
    id: "project-management",
    name: "Project Management",
    category: "Soft Skills",
  },
  { id: "code-review", name: "Code Review", category: "Soft Skills" },
  { id: "mentoring", name: "Mentoring", category: "Soft Skills" },
  {
    id: "technical-writing",
    name: "Technical Writing",
    category: "Soft Skills",
  },
];
